#https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html

server:
  port: 8050
  context-path: /oauth2

welcome:
  message: Welcome to Spring Boot OAuth2 Server !!

oauth:
  token.access.expired: 3600
  token.refresh.expired: 7200
  db.url: jdbc:postgresql://localhost:5439/ils
  db.driver: org.postgresql.Driver
  db.username: postgres
  db.password:


