#General
name: Development
version: 0.1
releaseDate: 1/1/2005
locale: EN
messageBundle: yml

# Api Server
server:
  port: 8070
  context-path: /api

# Database
db:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5433/ils
  username: postgres
  password: 123

# Hibernate
hibernate:
  dialect: org.hibernate.dialect.PostgreSQL82Dialect
  show_sql: true
  hbm2ddl.auto: update

# Entity Manager
entitymanager:
  packagesToScan: org.sanelib.ils.core
